### ISSUE TITLE
JaasClientOauthLoginCallbackHandler not working with Quarkus native

### ISSUE THREAD

**Issue by merlante** [strimzi/.github#1]
This issue might live with Quarkus or Graalvm, but I thought I'd start here.

I'm using Oauth authentication (kafka-oauth-client 0.7.1) with KafkaStreams on Quarkus (0.13.0) and the io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler class for kafka-streams.sasl.login.callback.handler.class (config at the end). This setup works, and I can login correctly in jvm mode. However, in native mode it does now work.

When I do:
> ./mvnw compile quarkus:dev

my app logs in with no problems.

However, when I do (on a mac -- but I have also see this with the container build and a docker run):
> ./mvnw clean package -Pnative

I get the exception, below. 

I believe that the issue is related to the use of java.net.URL in JaasClientOauthLoginCallbackHandler/HttpUtil (which is masked somewhat by the "LoginException: java.lang.IllegalArgumentException: Malformed token endpoint url"). I think it may be related or similar to:
- https://github.com/quarkusio/quarkus/issues/12447
- https://github.com/oracle/graal/pull/2889
- https://github.com/oracle/graal/issues/1721

Thanks,
mark

Stack trace (note I have X'ed out parts of the endpoint url, but it is good):

> 2021-04-06 14:17:55,621 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): javax.security.auth.login.LoginException: java.lang.IllegalArgumentException: Malformed token endpoint url: https://XXXXXXXXXXXXXX/auth/realms/XXXXXXX/protocol/openid-connect/token
>         at io.strimzi.kafka.oauth.common.HttpUtil.request(HttpUtil.java:96)
>         at io.strimzi.kafka.oauth.common.HttpUtil.request(HttpUtil.java:86)
>         at io.strimzi.kafka.oauth.common.HttpUtil.post(HttpUtil.java:62)
>         at io.strimzi.kafka.oauth.common.OAuthAuthenticator.post(OAuthAuthenticator.java:92)
>         at io.strimzi.kafka.oauth.common.OAuthAuthenticator.loginWithClientSecret(OAuthAuthenticator.java:60)
>         at io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler.handleCallback(JaasClientOauthLoginCallbackHandler.java:158)
>         at io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler.handle(JaasClientOauthLoginCallbackHandler.java:138)
>         at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.identifyToken(OAuthBearerLoginModule.java:316)
>         at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.login(OAuthBearerLoginModule.java:301)
>         at javax.security.auth.login.LoginContext.invoke(LoginContext.java:726)
>         at javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
>         at javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
>         at java.security.AccessController.doPrivileged(AccessController.java:147)
>         at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
>         at javax.security.auth.login.LoginContext.login(LoginContext.java:574)
>         at org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshingLogin.login(ExpiringCredentialRefreshingLogin.java:204)
>         at org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerRefreshingLogin.login(OAuthBearerRefreshingLogin.java:150)
>         at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62)
>         at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105)
>         at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:158)
>         at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:157)
>         at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:73)
>         at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
>         at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:508)
>         at org.apache.kafka.clients.admin.Admin.create(Admin.java:65)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer.<init>(KafkaStreamsProducer.java:91)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_Bean.create(KafkaStreamsProducer_Bean.zig:742)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_Bean.create(KafkaStreamsProducer_Bean.zig:762)
>         at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
>         at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
>         at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
>         at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
>         at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_Bean.get(KafkaStreamsProducer_Bean.zig:794)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_Bean.get(KafkaStreamsProducer_Bean.zig:810)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.create(KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.zig:136)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.create(KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.zig:154)
>         at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
>         at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
>         at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
>         at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
>         at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.get(KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.zig:186)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.get(KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.zig:202)
>         at org.acme.services.AvailableStockService_Bean.create(AvailableStockService_Bean.zig:167)
>         at org.acme.services.AvailableStockService_Bean.create(AvailableStockService_Bean.zig:207)
>         at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
>         at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
>         at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
>         at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
>         at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
>         at org.acme.services.AvailableStockService_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(AvailableStockService_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:135)
>         at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:283)
>         at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:268)
>         at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:70)
>         at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
>         at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
>         at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:87)
>         at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
>         at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:653)
>         at io.quarkus.runtime.Application.start(Application.java:90)
>         at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
>         at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
> 
>         at javax.security.auth.login.LoginContext.invoke(LoginContext.java:821)
>         at javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
>         at javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
>         at java.security.AccessController.doPrivileged(AccessController.java:147)
>         at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
>         at javax.security.auth.login.LoginContext.login(LoginContext.java:574)
>         at org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshingLogin.login(ExpiringCredentialRefreshingLogin.java:204)
>         at org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerRefreshingLogin.login(OAuthBearerRefreshingLogin.java:150)
>         at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62)
>         at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105)
>         at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:158)
>         at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:157)
>         at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:73)
>         at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
>         at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:508)
>         at org.apache.kafka.clients.admin.Admin.create(Admin.java:65)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer.<init>(KafkaStreamsProducer.java:91)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_Bean.create(KafkaStreamsProducer_Bean.zig:742)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_Bean.create(KafkaStreamsProducer_Bean.zig:762)
>         at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
>         at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
>         at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
>         at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
>         at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_Bean.get(KafkaStreamsProducer_Bean.zig:794)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_Bean.get(KafkaStreamsProducer_Bean.zig:810)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.create(KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.zig:136)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.create(KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.zig:154)
>         at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
>         at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
>         at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
>         at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
>         at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.get(KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.zig:186)
>         at io.quarkus.kafka.streams.runtime.KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.get(KafkaStreamsProducer_ProducerMethod_getKafkaStreams_7790cbc0b67cec783271544399d0fa71077d93dc_Bean.zig:202)
>         at org.acme.services.AvailableStockService_Bean.create(AvailableStockService_Bean.zig:167)
>         at org.acme.services.AvailableStockService_Bean.create(AvailableStockService_Bean.zig:207)
>         at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
>         at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
>         at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
>         at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
>         at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
>         at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
>         at org.acme.services.AvailableStockService_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(AvailableStockService_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:135)
>         at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:283)
>         at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:268)
>         at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:70)
>         at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
>         at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
>         at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:87)
>         at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
>         at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:653)
>         at io.quarkus.runtime.Application.start(Application.java:90)
>         at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
>         at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
>         at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)

Quarkus oauth config (from application.properties):

> quarkus.kafka-streams.security.protocol=SASL_SSL
> quarkus.kafka-streams.sasl.mechanism=OAUTHBEARER
> quarkus.kafka-streams.sasl.jaas-config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
>   oauth.client.id="${USER}" \
>   oauth.client.secret="${PASSWORD}" \
>   oauth.token.endpoint.uri="${ENDPOINT_URL}" ;
> kafka-streams.sasl.login.callback.handler.class=io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler

**Comment by merlante** [comment]
This issue did not appear in the right place. I have created a new issue in strimzi-kafka-oauth.
